export default {
  informations: {
    id: 'AGB_A2CP_EUR',
    name: 'Castlevania - Aria of Sorrow',
    checkFile: [0x43, 0x41, 0x53, 0x54, 0x4c, 0x45, 0x56, 0x41, 0x4e, 0x49, 0x41, 0x32, 0x2d, 0x30, 0x31, 0x30],
  },
  sections: {
    stats: {
      name: 'Stats',
      values: {
        level: {
          offset: 0x2d,
          octets: 8,
          name: 'Level',
          type: 'number',
          inputProps: {
            min: 1,
            max: 99,
          },
        },
        hp: {
          offset: 0x2e,
          octets: 16,
          name: 'HP',
          type: 'number',
          inputProps: {
            min: 1,
            max: 9999,
          },
        },
        hpMax: {
          offset: 0x32,
          octets: 16,
          name: 'HP Max',
          type: 'number',
          inputProps: {
            min: 1,
            max: 9999,
          },
        },
        mp: {
          offset: 0x30,
          octets: 16,
          name: 'MP',
          type: 'number',
          inputProps: {
            min: 0,
            max: 9999,
          },
        },
        mpMax: {
          offset: 0x34,
          octets: 16,
          name: 'MP Max',
          type: 'number',
          inputProps: {
            min: 0,
            max: 9999,
          },
        },
        strength: {
          offset: 0x36,
          octets: 16,
          name: 'Strength',
          type: 'number',
          inputProps: {
            min: 1,
            max: 999,
          },
        },
        constitution: {
          offset: 0x38,
          octets: 16,
          name: 'Constitution',
          type: 'number',
          inputProps: {
            min: 1,
            max: 999,
          },
        },
        intelligence: {
          offset: 0x3a,
          octets: 16,
          name: 'Intelligence',
          type: 'number',
          inputProps: {
            min: 1,
            max: 999,
          },
        },
        luck: {
          offset: 0x3c,
          octets: 16,
          name: 'Luck',
          type: 'number',
          inputProps: {
            min: 1,
            max: 999,
          },
        },
        experience: {
          offset: 0x40,
          octets: 32,
          name: 'Experience',
          type: 'number',
          inputProps: {
            min: 0,
            max: 99999999,
          },
        },
        gold: {
          offset: 0x44,
          octets: 32,
          name: 'Gold',
          type: 'number',
          inputProps: {
            min: 0,
            max: 999999,
          },
        },
        time: {
          offset: 0x1b8,
          octets: 32,
          name: 'Time',
          type: 'time',
          inputProps: {
            step: 1,
          },
        },
        // previewName: {
        //   offset: [0x1A0, 8],
        //   octets: 8,
        //   name: 'Name',
        //   type: 'text',
        // },
        // previewGold: {
        //   offset: 0x1B4,
        //   octets: 32,
        //   name: 'Preview Gold',
        //   type: 'number',
        //   hidden: true,
        // },
      },
    },
    equipment: {
      name: 'Items & Equipment',
      tabs: {
        items: {
          name: 'Items',
          list: {
            offset: 0x48,
            octets: 8,
            type: 'number',
            inputProps: {
              min: 0,
              max: 9,
            },
            names: [
              'Potion',
              'High Potion',
              'Super Potion',
              'Meat Strip',
              'Tasty Meat',
              'Mind Up',
              'High Mind Up',
              'Mana Prism',
              'Anti-Venom',
              'Uncurse Potion',
              'Potato Pancake',
              'Beef Curry',
              'Ramen',
              'Cream Soda',
              'Cream Puff',
              'Milk',
              'Coffee',
              'Tea',
              'Pudding',
              'Strawberry',
              'Melon',
              'Grapes',
              'Persimmon',
              'Rotten Meat',
              'Spoiled Milk',
              'Skeleteon Key',
              'Ancient Book 1',
              'Ancient Book 2',
              'Ancient Book 3',
              'CASTLE MAP 1',
              'CASTLE MAP 2',
              'CASTLE MAP 3',
            ],
          },
        },
        weapons: {
          name: 'Weapons',
          list: {
            offset: 0x68, // Weapons: 0x68 > 0xa2
            octets: 8,
            type: 'number',
            inputProps: {
              min: 0,
              max: 9,
            },
            names: [
              'Knife',
              'Baselard',
              'Combat Knife',
              'Short Sword',
              'Bastard Sword',
              'Whip Sword',
              'Gladius',
              'Gram',
              "Milican's Sword",
              'Hrunting',
              'Mystletain',
              "Rahab's Sword",
              'Durandal',
              'Laevatain',
              'Burtgang',
              'Kaladbolg',
              'Vjaya',
              'Balmung',
              'Broadsword',
              'Scimitar',
              'Claymore',
              'Great Sword',
              'Joyeuse',
              'Dainslef',
              'Ascalon',
              'Claimh Solais',
              'Final Sword',
              'Bamboo Sword',
              'Katana',
              'Osafune',
              'Onikiri',
              'Kunitsuna',
              'Yasutsuna',
              'Muramasa',
              'Hammer',
              'Warhammer',
              'Excalibur',
              'Tallhammer',
              'Battle Axe',
              "Death's Sickle",
              'Rapier',
              'Estoc',
              'Cutall',
              'Spear',
              'Trident',
              'Lance',
              'Partizan',
              'Gabolg',
              'Gungner',
              "Ronginus' Spear",
              'Cestus',
              'Kaiser Knuckle',
              'Mach Punch',
              'Whip Knuckle',
              'Poison Fist',
              'Handgun',
              'Silver Gun',
              'Positron Rifle',
              'Valmanway',
            ],
          },
        },
        armors: {
          name: 'Armors',
          list: {
            offset: 0xa3,
            octets: 8,
            type: 'number',
            inputProps: {
              min: 0,
              max: 9,
            },
            names: [
              'Casual Clothes',
              'Cloth Tunic',
              'Gym Clothes',
              'War Fatigues',
              'Ninja Suit',
              'Soldier Uniform',
              'Pitch Black Suit',
              "Olrox's Suit",
              "Dracula's Tunic",
              'Leather Plate',
              'Copper Plate',
              'Iron Plate',
              'Steel Plate',
              'Silver Plate',
              'Gold Plate',
              'Eversing',
              'Samurai Armor',
              'Silk Robe',
              'Elfin Robe',
              "Death's Robe",
              "Demon's Mail",
              'Armor of Fire',
              'Armor of Water',
              'Blocking Mail',
              'Army Jacket',
            ],
          },
        },
        accessories: {
          name: 'Accessories',
          list: {
            offset: 0xbc,
            octets: 8,
            type: 'number',
            inputProps: {
              min: 0,
              max: 9,
            },
            names: [
              'Cape',
              'Crimson Cloak',
              'Black Cloak',
              'Pendant',
              'Heart Pendant',
              'Scarf',
              'Red Scarf',
              'Ancient Belt',
              'Black Belt',
              'Skull Necklace',
              'Flame Necklace',
              "Satan's Ring",
              'Tear of Blood',
              'Lucky Charm',
              'Rare Ring',
              'Soul Eater Ring',
              'Rune Ring',
              'Sherman Ring',
              'Gold Ring',
              'Chaos Ring',
            ],
          },
        },
      },
    },
    souls: {
      name: 'Souls', // 2 slots par hex, 15 quantité par slots (00 = Rien, 01 = 1 au Slot 1, 0F = 15 au Slot 1, 10 = 1 au Slot 2, 12 = 2 au Slot 1 et 1 au Slot 2 etc.)
      values: {
        wingedSkeleton: {
          offset: 0xd0, // Souls: 0xd0 > 0xeb
          octets: 8,
          name: 'Winged Skeleton',
          type: 'number',
          inputProps: {
            min: 0,
            max: 15,
          },
        },
      },
    },
    abilities: {
      name: 'Abilities', // 2 slots par hex (00 = Rien, 01 = Slot 1, (10 = Slot 2 > Non confirmé), 11 = Slot 1 et 2)
      values: {
        graveKeeper: {
          offset: 0x146, // 0x147, 0x148
          octets: 8,
          name: 'Grave Keeper',
          type: 'checkbox',
        },
      },
    },
    bestiary: {
      name: 'Bestiary', // 8 slots par hex (00 = Rien, 01 = Slot 1, 02 = Slot 2, 03 = Slot 1 et 2 etc.)
      values: {
        bat: {
          offset: 0x154, // Bestiary: 0x154 > 0x161
          octets: 8,
          name: 'Bat',
          type: 'checkbox',
        },
      },
    },
    // map: {
    //   name: 'Map', // 0x268 = Visited, 0x26c = Grey
    //   values: {
    //     graveKeeper: {
    //       offset: 0x268,
    //       octets: 8,
    //       name: 'Grave Keeper',
    //       type: 'checkbox',
    //     },
    //   },
    // },
  },
};
